package FjoSpidie::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

=head1 NAME

FjoSpidie::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<FjoSpidie>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<FjoSpidie::Schema>

=cut

sub reports {
    my $self = shift;
    return $self->schema->resultset('Report')->search(
        { endtime => { '!=', "0000-00-00 00:00:00" } },
        {
            order_by => { -desc => 'me.starttime' },
            prefetch => 'alerts'
        },
    );
}

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Espen Fjellvær Olsen

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
